# Generated by Django 5.0.6 on 2024-07-16 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='postal_code',
            field=models.PositiveIntegerField(blank=True, max_length=20, null=True),
        ),
    ]
