# Generated by Django 5.0.6 on 2024-07-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_manufacturer_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='postal_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='tin',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
