# Generated by Django 5.0.6 on 2024-07-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_manufacturer_postal_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hsn',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='map_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_spec',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_of_measurement',
            field=models.CharField(blank=True, choices=[('centimeter', 'Centimeter'), ('gallon', 'Gallon'), ('liter', 'Liter'), ('meter', 'Meter'), ('metric_ton', 'Metric Ton'), ('milligram', 'Milligram'), ('pound', 'Pound')], max_length=30, null=True),
        ),
    ]
