# Generated by Django 5.0.6 on 2024-07-17 05:07

import apps.billing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_product_hsn_product_map_code_product_product_spec_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='billing_stat',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('on_approval', 'On Approval'), ('suspended', 'Suspended')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='gstin',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[apps.billing.models.validate_gstin]),
        ),
        migrations.AddField(
            model_name='customer',
            name='id_no',
            field=models.CharField(blank=True, choices=[('cash_paid_to', 'Cash Paid To'), ('cash_received_from', 'Cash Received From'), ('salary_for_the_month', 'Salary For The Month'), ('sale_of_floppy_disks', 'Sale of Floppy Disks'), ('sale_of_keyboards', 'Sale of Keyboards'), ('tour_bills_paid_to', 'Tour Bills Paid To'), ('transfer_from_bank', 'Transfer From Bank')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='license1',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='license2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='postal_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='sale_type',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('credit', 'Credit'), ('cheque', 'Cheque'), ('sign_bill', 'Sign Bill'), ('bank', 'Bank'), ('direct', 'Direct'), ('adv_payment', 'Adv.Pymt')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(blank=True, choices=[('within_state', 'Within State'), ('outside_state', 'Outside State'), ('sale_nil_gst', 'Sale(NIL GST)')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='state_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
