# Generated by Django 5.0.6 on 2024-07-17 09:19

import apps.billing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_customer_billing_stat_customer_city_customer_gstin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='area',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Area'),
        ),
        migrations.AddField(
            model_name='customer',
            name='carrier',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Carrier'),
        ),
        migrations.AddField(
            model_name='customer',
            name='cst',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='CST'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_representative',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Representative'),
        ),
        migrations.AddField(
            model_name='customer',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='tin',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='TIn'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gstin',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[apps.billing.models.validate_gstin], verbose_name='GSTIN'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='id_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
