# Generated by Django 5.0.6 on 2024-07-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_customer_area_customer_carrier_customer_cst_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Mb No'),
        ),
    ]
