# Generated by Django 5.0.7 on 2024-07-22 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_rename_state_customer_sale_state_customer_state_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='class_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='contact1',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='contact2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='fax',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='price_option',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='price_table',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
