# Generated by Django 5.0.7 on 2024-07-22 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_customer_class_name_customer_contact1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='contact',
        ),
    ]
