# Generated by Django 5.0.7 on 2024-07-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_remove_customer_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufacturer',
            old_name='contact',
            new_name='contact1',
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='area',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Area'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='class_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='contact2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='cst',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='CST'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='customer_representative',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Representative'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='fax',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='formIR',
            field=models.CharField(blank=True, choices=[('issue', 'Issue'), ('receive', 'Receive')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='invoice_prefix',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='margin_percentage',
            field=models.PositiveSmallIntegerField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Mb No'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='purchase_account',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='sale_state',
            field=models.CharField(blank=True, choices=[('within_state', 'Within State'), ('outside_state', 'Outside State'), ('sale_nil_gst', 'Sale(NIL GST)')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='state_code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='state_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='std_form',
            field=models.CharField(blank=True, choices=[('form_c', 'Form C'), ('form_d', 'Form D'), ('form_37', 'Form 37')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='telephone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
