# Generated by Django 5.0.7 on 2024-07-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_rename_contact_manufacturer_contact1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bin_loc',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='igst',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_taxes_charges',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sgst',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='taxes_buying_rate',
            field=models.CharField(blank=True, choices=[('excluded', 'Excluded'), ('included', 'Included')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='taxes_selling_rate',
            field=models.CharField(blank=True, choices=[('excluded', 'Excluded'), ('included', 'Included')], max_length=15, null=True),
        ),
    ]
