# Generated by Django 5.0.7 on 2024-07-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_product_bin_loc_product_igst_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_code',
        ),
        migrations.RemoveField(
            model_name='productgroup',
            name='consolidation_code',
        ),
        migrations.AddField(
            model_name='product',
            name='sh_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='consolidation_status',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='margin_percentage',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
