# Generated by Django 5.0.7 on 2024-07-23 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_remove_product_product_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.PositiveIntegerField(blank=True, null=True)),
                ('state_name', models.CharField(blank=True, max_length=50, null=True)),
                ('sale_state', models.CharField(blank=True, choices=[('within_state', 'Within State'), ('outside_state', 'Outside State'), ('sale_nil_gst', 'Sale(NIL GST)')], max_length=50, null=True)),
                ('state_code', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'Address',
                'ordering': ['-id'],
            },
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='sale_state',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='state_code',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='state_name',
        ),
        migrations.AlterField(
            model_name='customer',
            name='carrier',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cst',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_representative',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tin',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='customer_representative',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturer_location', to='billing.location'),
        ),
    ]
