# Generated by Django 5.0.7 on 2024-07-24 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_location_remove_manufacturer_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='sale_state',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='state_code',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='state_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_location', to='billing.location'),
        ),
        migrations.AlterModelTable(
            name='location',
            table='Location',
        ),
    ]
