# Generated by Django 5.0.7 on 2024-07-24 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_remove_customer_address_remove_customer_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_category', models.CharField(blank=True, choices=[('sales_taxes', 'Sales Taxes'), ('purchase_taxes', 'Purchase Taxes')], max_length=25, null=True)),
                ('tax_type', models.CharField(blank=True, choices=[('sgst_cgst', 'SGST/CGST (Intrastate Sales)'), ('igst', 'IGST (InterState Sales)')], max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaxDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('sgst', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cgst', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('igst', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('tax_category_and_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_details', to='billing.taxstructure')),
            ],
        ),
    ]
