# Generated by Django 5.0.7 on 2024-07-25 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_taxstructure_taxdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxdetail',
            old_name='tax_category_and_type',
            new_name='tax_structure',
        ),
    ]
