# Generated by Django 5.0.7 on 2024-07-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_rename_tax_category_and_type_taxdetail_tax_structure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxdetail',
            name='tax_structure',
        ),
        migrations.RemoveField(
            model_name='taxstructure',
            name='tax_category',
        ),
        migrations.AddField(
            model_name='taxstructure',
            name='cgst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='taxstructure',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='taxstructure',
            name='igst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='taxstructure',
            name='sgst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='taxstructure',
            name='tax_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='taxdetail',
            name='tax_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='taxstructure',
            name='tax_type',
            field=models.CharField(blank=True, choices=[('sales_taxes', 'Sales Taxes'), ('purchase_taxes', 'Purchase Taxes')], max_length=25, null=True),
        ),
    ]
