# Generated by Django 5.0.7 on 2024-07-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_remove_taxdetail_tax_structure_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaxDetail',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company_id_no',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='fax',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Mb No'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='state_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='telephone1',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='telephone2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='telephone3',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
