# Generated by Django 5.0.7 on 2024-08-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0020_salesrep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='postal_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesrep',
            name='postal_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
