# Generated by Django 5.0.7 on 2024-08-02 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0021_alter_companyprofile_postal_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrep',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_rep', to='billing.manufacturer'),
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('sh_name', models.CharField(blank=True, max_length=30, null=True)),
                ('pin_code', models.PositiveIntegerField(blank=True, null=True)),
                ('fm_name', models.CharField(blank=True, max_length=20, null=True)),
                ('area_status', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=20, null=True)),
                ('area_rep1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area_rep1', to='billing.salesrep')),
                ('area_rep2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area_rep2', to='billing.salesrep')),
                ('area_rep3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area_rep3', to='billing.salesrep')),
                ('area_under', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subarea', to='billing.area')),
            ],
        ),
    ]
