# Generated by Django 5.0.7 on 2024-08-03 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0022_alter_salesrep_company_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='area_rep1',
        ),
        migrations.RemoveField(
            model_name='area',
            name='area_rep2',
        ),
        migrations.RemoveField(
            model_name='area',
            name='area_rep3',
        ),
        migrations.RemoveField(
            model_name='area',
            name='area_under',
        ),
        migrations.RemoveField(
            model_name='area',
            name='fm_name',
        ),
        migrations.RemoveField(
            model_name='salesrep',
            name='under',
        ),
        migrations.CreateModel(
            name='CustomerManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_manufacturer', to='billing.area')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_manufacturer', to='billing.manufacturer')),
                ('representative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_manufacturer', to='billing.salesrep')),
            ],
            options={
                'unique_together': {('manufacturer', 'area', 'representative')},
            },
        ),
    ]
