# Generated by Django 5.0.7 on 2024-08-03 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0023_remove_area_area_rep1_remove_area_area_rep2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='CustomerManufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='billing.customermanufacturer'),
        ),
    ]
