# Generated by Django 5.0.7 on 2024-08-03 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0024_customer_customermanufacturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesrep',
            name='company',
        ),
    ]
