# Generated by Django 5.0.7 on 2024-08-05 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0025_remove_salesrep_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='CustomerManufacturer',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='area',
        ),
        migrations.CreateModel(
            name='ManufacturerArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_area', to='billing.area')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_area', to='billing.customer')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_area', to='billing.manufacturer')),
            ],
            options={
                'unique_together': {('customer', 'manufacturer', 'area')},
            },
        ),
        migrations.DeleteModel(
            name='CustomerManufacturer',
        ),
    ]
