# Generated by Django 5.0.7 on 2024-08-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0026_remove_customer_customermanufacturer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='is_auto',
            field=models.BooleanField(default=False),
        ),
    ]
