# Generated by Django 5.0.7 on 2024-08-05 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0027_area_is_auto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ('-id',)},
        ),
    ]
