# Generated by Django 5.0.7 on 2024-08-05 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0028_alter_area_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ('name',)},
        ),
    ]
