# Generated by Django 5.0.7 on 2024-08-05 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0029_alter_area_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={},
        ),
    ]
