# Generated by Django 5.0.7 on 2024-08-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0030_alter_area_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='is_auto',
        ),
        migrations.AddField(
            model_name='customer',
            name='is_auto_area',
            field=models.BooleanField(default=False),
        ),
    ]
