# Generated by Django 5.0.7 on 2024-08-06 06:35

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0031_remove_area_is_auto_customer_is_auto_area'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='salesrep',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='is_auto_rep',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ManufacturerRep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_rep', to='billing.customer')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_rep', to='billing.manufacturer')),
                ('sales_rep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_rep', to='billing.salesrep')),
            ],
            options={
                'unique_together': {('customer', 'manufacturer', 'sales_rep')},
            },
        ),
    ]
