# Generated by Django 5.0.7 on 2024-08-06 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0032_alter_salesrep_managers_customer_is_auto_rep_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_representative',
        ),
    ]
