# Generated by Django 5.0.7 on 2024-08-06 12:12

import apps.billing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0033_remove_customer_customer_representative'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carriers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('sh_name', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.TextField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.PositiveIntegerField(blank=True, null=True)),
                ('state_name', models.CharField(blank=True, max_length=50, null=True)),
                ('telephone', models.CharField(blank=True, max_length=15, null=True)),
                ('fax', models.CharField(blank=True, max_length=20, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Mb No')),
                ('gstin', models.CharField(max_length=15, validators=[apps.billing.models.validate_gstin])),
                ('e_way_id', models.CharField(max_length=12)),
                ('regn_no', models.CharField(max_length=15)),
                ('remarks', models.TextField(max_length=100)),
            ],
        ),
        migrations.AlterModelManagers(
            name='salesrep',
            managers=[
            ],
        ),
    ]
