# Generated by Django 5.0.7 on 2024-08-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0034_carriers_alter_salesrep_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carriers',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='carriers',
            name='e_way_id',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='carriers',
            name='regn_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='carriers',
            name='remarks',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
