# Generated by Django 5.0.7 on 2024-08-06 12:19

import apps.billing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0035_alter_carriers_city_alter_carriers_e_way_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carriers',
            name='gstin',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[apps.billing.models.validate_gstin]),
        ),
    ]
