# Generated by Django 5.0.7 on 2024-08-07 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0038_departments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('sh_name', models.CharField(blank=True, max_length=30, null=True)),
                ('division_id', models.PositiveSmallIntegerField(blank=True, max_length=30, null=True, unique=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.customer')),
            ],
        ),
    ]
