# Generated by Django 5.0.7 on 2024-08-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0039_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='division_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True, unique=True),
        ),
    ]
