# Generated by Django 5.0.7 on 2024-08-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0040_alter_division_division_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('sh_name', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='departments',
            name='sh_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='division',
            name='sh_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='units',
            name='sh_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
