# Generated by Django 5.0.7 on 2024-08-08 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0042_customerclass_uom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='manufacturer',
            name='customer_representative',
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='customer_class',
            field=models.ForeignKey(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.customerclass'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='sales_representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.salesrep'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.area'),
        ),
    ]
