# Generated by Django 5.0.7 on 2024-08-08 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0043_remove_manufacturer_class_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='carriers',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='companyprofile',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='customerclass',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='departments',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='discountclass',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='division',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='manufacturerrep',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='taxstructure',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='units',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='uom',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='sales_representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.salesrep'),
        ),
        migrations.AlterModelTable(
            name='account',
            table='Account',
        ),
        migrations.AlterModelTable(
            name='area',
            table='Area',
        ),
        migrations.AlterModelTable(
            name='carriers',
            table='Carriers',
        ),
        migrations.AlterModelTable(
            name='companyprofile',
            table='CompanyProfile',
        ),
        migrations.AlterModelTable(
            name='customerclass',
            table='CustomerClass',
        ),
        migrations.AlterModelTable(
            name='departments',
            table='Departments',
        ),
        migrations.AlterModelTable(
            name='discountclass',
            table='DiscountClass',
        ),
        migrations.AlterModelTable(
            name='division',
            table='Division',
        ),
        migrations.AlterModelTable(
            name='manufacturerrep',
            table='ManufacturerRep',
        ),
        migrations.AlterModelTable(
            name='taxstructure',
            table='TaxStructure',
        ),
        migrations.AlterModelTable(
            name='units',
            table='Units',
        ),
        migrations.AlterModelTable(
            name='uom',
            table='UOM',
        ),
    ]
