# Generated by Django 5.0.7 on 2024-08-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0044_alter_account_options_alter_area_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('sh_name', models.CharField(blank=True, max_length=10, null=True)),
                ('brand_code', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'BrandName',
                'ordering': ['-id'],
            },
        ),
    ]
