# Generated by Django 5.0.7 on 2024-08-08 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0045_brandname'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(blank=True, choices=[('bank', 'Bank'), ('payment_mode', 'Payment Mode')], max_length=15, null=True)),
            ],
            options={
                'db_table': 'PaymentMethod',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('domination_breakup', models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO')], max_length=5, null=True)),
                ('type_id', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('payment_mode', models.CharField(blank=True, choices=[('cards_coupon', 'Cards/Coupons'), ('cash', 'Cash'), ('credit', 'Credit'), ('others', 'Others')], max_length=20, null=True)),
                ('account_link', models.CharField(blank=True, max_length=10, null=True)),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.paymentmethod')),
            ],
            options={
                'db_table': 'PaymentDetails',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.paymentmethod')),
            ],
            options={
                'db_table': 'BankDetails',
                'ordering': ['-id'],
            },
        ),
    ]
