# Generated by Django 5.0.7 on 2024-08-08 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0046_paymentmethod_paymentdetails_bankdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankdetails',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='paymentdetails',
            name='payment_method',
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
    ]
