# Generated by Django 5.0.7 on 2024-08-09 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0047_remove_bankdetails_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='billing.carriers'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='class_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='billing.customerclass'),
        ),
        migrations.AlterField(
            model_name='division',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='division_customer', to='billing.customer'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturer', to='billing.area'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='customer_class',
            field=models.ForeignKey(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturer', to='billing.customerclass'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='sales_representative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturer', to='billing.salesrep'),
        ),
    ]
