# Generated by Django 3.2.6 on 2024-06-24 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='buy_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='sell_rate',
            field=models.FloatField(),
        ),
    ]
