# Generated by Django 5.0.6 on 2024-06-28 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customer_product_contact_alter_manufacturer_hsn_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='net_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
