# Generated by Django 5.0.6 on 2024-07-01 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_receipt_net_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='receipt_status',
            field=models.CharField(default='received', max_length=20),
        ),
    ]
