# Generated by Django 5.0.6 on 2024-07-01 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_receipt_receipt_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='receipt_status',
            field=models.CharField(choices=[('purchases', [('received', 'Received'), ('transit', 'Transit'), ('approved', 'Approved'), ('suspense', 'Suspense')]), ('adjustments', [('adjustment', 'Adjustment'), ('transfer', 'Transfer'), ('suspense', 'Suspense')]), ('opening_stock', [('none', 'None')])], default='received', max_length=20),
        ),
    ]
