# Generated by Django 5.0.6 on 2024-07-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_receipt_receipt_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='address',
            field=models.TextField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='print_name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='type',
            field=models.CharField(choices=[('manufacturer', 'Manufacturer'), ('supplier', 'Supplier')], default='manufacturer', max_length=20),
        ),
    ]
