# Generated by Django 5.0.6 on 2024-07-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_manufacturer_address_manufacturer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='address',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='sh_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
