# Generated by Django 5.0.6 on 2024-07-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_product_buy_rate_alter_product_mrp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='hsn_code',
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
