# Generated by Django 5.0.6 on 2024-07-02 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_manufacturer_hsn_code_alter_manufacturer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_group', to='home.group'),
        ),
    ]
