# Generated by Django 5.0.6 on 2024-07-03 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_product_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturer',
            options={},
        ),
        migrations.AlterField(
            model_name='group',
            name='group_name',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
