# Generated by Django 5.0.6 on 2024-07-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_customer_options_alter_group_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, related_name='customer', to='home.product'),
        ),
    ]
