# Generated by Django 5.0.6 on 2024-07-03 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_customer_product'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='Customer',
        ),
        migrations.AlterModelTable(
            name='group',
            table='Group',
        ),
        migrations.AlterModelTable(
            name='manufacturer',
            table='Manufacturer',
        ),
        migrations.AlterModelTable(
            name='product',
            table='Product',
        ),
        migrations.AlterModelTable(
            name='receipt',
            table='Receipt',
        ),
        migrations.AlterModelTable(
            name='receiptproduct',
            table='ReceiptProduct',
        ),
    ]
