# Generated by Django 5.0.6 on 2024-07-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_customer_table_alter_group_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_name',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
