# Generated by Django 5.0.6 on 2024-07-03 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_customer_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='product',
        ),
    ]
