# Generated by Django 5.0.6 on 2024-07-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_customer_last_accessed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='net_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='receiptproduct',
            name='product',
        ),
        migrations.AddField(
            model_name='receiptproduct',
            name='product',
            field=models.ManyToManyField(related_name='receipt_products', to='home.product'),
        ),
    ]
