# Generated by Django 5.0.6 on 2024-07-09 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_product_net_quantity_remove_receiptproduct_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiptproduct',
            name='product',
        ),
        migrations.AddField(
            model_name='receiptproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipt_products', to='home.product'),
        ),
    ]
