# Generated by Django 5.0.6 on 2024-07-11 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_remove_receiptproduct_product_receiptproduct_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='ProductGroup',
        ),
    ]
