# Generated by Django 5.0.6 on 2024-07-11 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_rename_group_productgroup'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productgroup',
            table='ProductGroup',
        ),
    ]
